# -*- coding: utf-8 -*-
"""MachineLearning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SPF81e3k-n3m7dixcBFdYUmQNPTkvS_O
"""

from google.colab import drive
drive.mount('/content/drive')

"""# Mall Customers"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

def load_data(file_path):
    return pd.read_csv(file_path)

def visualize_mall_customers(df):
    plt.figure(figsize=(15, 10))

    # 1. Age Distribution
    plt.subplot(2, 2, 1)
    sns.histplot(df['Age'], bins=20, kde=True, color='skyblue')
    plt.title('Age Distribution')
    plt.xlabel('Age')
    plt.ylabel('Frequency')

    # 2. Annual Income Distribution
    plt.subplot(2, 2, 2)
    sns.histplot(df['Annual_Income_(k$)'], bins=20, kde=True, color='orange')
    plt.title('Annual Income Distribution')
    plt.xlabel('Annual Income (k$)')
    plt.ylabel('Frequency')

    # 3. Spending Score Distribution
    plt.subplot(2, 2, 3)
    sns.histplot(df['Spending_Score'], bins=20, kde=True, color='green')
    plt.title('Spending Score Distribution')
    plt.xlabel('Spending Score')
    plt.ylabel('Frequency')

    # 4. Income vs Spending Score Scatter Plot
    plt.subplot(2, 2, 4)
    sns.scatterplot(data=df, x='Annual_Income_(k$)', y='Spending_Score', hue='Genre', alpha=0.7)
    plt.title('Income vs Spending Score by Gender')
    plt.xlabel('Annual Income (k$)')
    plt.ylabel('Spending Score')

    plt.show()

file_path = "/content/drive/MyDrive/Mall_Customers.csv"
df = load_data(file_path)
visualize_mall_customers(df)

"""# Spam"""

def load_spam_data(file_path):
    df = pd.read_csv(file_path, encoding='latin-1')[['Category', 'Message']]
    df.columns = ['Label', 'Text']
    return df

def visualize_spam_data(df):

    plt.figure(figsize=(14, 10))

    #  Count of spam vs ham
    plt.subplot(2, 2, 1)
    sns.countplot(data=df, x='Label', palette='pastel')
    plt.title('Spam vs Ham Count')
    plt.xlabel('Message Type')
    plt.ylabel('Count')


    plt.show()


path = "/content/drive/MyDrive/spam.csv"
df_spam = load_spam_data(path)
visualize_spam_data(df_spam)

"""# weight-height"""

df = pd.read_csv("/content/drive/MyDrive/weight-height.csv")

# Create a 1x3 subplot layout
fig, axes = plt.subplots(1, 3, figsize=(18, 5))

# 1. Height vs Weight Scatter Plot
sns.scatterplot(data=df, x="Height", y="Weight", hue="Gender", alpha=0.6, ax=axes[0])
axes[0].set_title("Height vs. Weight by Gender")

# 2. Distribution of Height by Gender
sns.histplot(data=df, x="Height", hue="Gender", kde=True, element="step", ax=axes[1])
axes[1].set_title("Height Distribution by Gender")

# 3. Distribution of Weight by Gender
sns.histplot(data=df, x="Weight", hue="Gender", kde=True, element="step", ax=axes[2])
axes[2].set_title("Weight Distribution by Gender")

plt.tight_layout()
plt.show()

